[mgr]
ratio = [0, 2, 5]

[preview]
max_width = 2000
max_height = 2000
image_filter = "lanczos3"
image_quality = 90

[opener]
edit = [
  {run = "nvim %s", desc = "Neovim", block = true, for = "unix"},
]
